import type { Achievement } from '@/types/gamification';

export const STORAGE_KEY = 'cz-learning-progress';

export const XP_REWARDS = {
  stepComplete: 10,
  lessonComplete: 50,
  fillBlanksPerfect: 25,
  flashcardSession: 20,
  moduleComplete: 100,
  dailyLogin: 10,
  dailyGoalMet: 30,
  streakMilestone3: 50,
  streakMilestone7: 100,
  streakMilestone14: 200,
  streakMilestone30: 500,
} as const;

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first-lesson',
    title: 'První krok',
    titleEn: 'First Step',
    description: 'Complete your first lesson',
    icon: '🌟',
    category: 'milestone',
    condition: { type: 'complete_lessons', count: 1 },
    xpReward: 50,
  },
  {
    id: 'five-lessons',
    title: 'Pět lekcí',
    titleEn: 'Five Lessons',
    description: 'Complete 5 lessons',
    icon: '📚',
    category: 'milestone',
    condition: { type: 'complete_lessons', count: 5 },
    xpReward: 100,
  },
  {
    id: 'ten-lessons',
    title: 'Deset lekcí',
    titleEn: 'Ten Lessons',
    description: 'Complete 10 lessons',
    icon: '🏆',
    category: 'milestone',
    condition: { type: 'complete_lessons', count: 10 },
    xpReward: 200,
  },
  {
    id: 'streak-3',
    title: 'Tři dny v řadě',
    titleEn: 'Hat Trick',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    category: 'streak',
    condition: { type: 'streak_days', count: 3 },
    xpReward: 100,
  },
  {
    id: 'streak-7',
    title: 'Týdenní válečník',
    titleEn: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '⚔️',
    category: 'streak',
    condition: { type: 'streak_days', count: 7 },
    xpReward: 250,
  },
  {
    id: 'streak-14',
    title: 'Dvoutýdenní rekord',
    titleEn: 'Fortnight Force',
    description: 'Maintain a 14-day streak',
    icon: '💪',
    category: 'streak',
    condition: { type: 'streak_days', count: 14 },
    xpReward: 500,
  },
  {
    id: 'xp-500',
    title: 'Půl tisícovky',
    titleEn: 'Half K',
    description: 'Earn 500 XP',
    icon: '💎',
    category: 'milestone',
    condition: { type: 'total_xp', amount: 500 },
    xpReward: 100,
  },
  {
    id: 'xp-1000',
    title: 'Tisícovka',
    titleEn: 'Kilopoint',
    description: 'Earn 1,000 XP',
    icon: '👑',
    category: 'milestone',
    condition: { type: 'total_xp', amount: 1000 },
    xpReward: 200,
  },
  {
    id: 'module-complete-01',
    title: 'Pozdravy zvládnuty',
    titleEn: 'Greetings Mastered',
    description: 'Complete the Greetings module',
    icon: '👋',
    category: 'mastery',
    condition: { type: 'complete_module', moduleId: '01-greetings' },
    xpReward: 150,
  },
  {
    id: 'module-complete-02',
    title: 'Jídelní expert',
    titleEn: 'Food Expert',
    description: 'Complete the Food Ordering module',
    icon: '🍽️',
    category: 'mastery',
    condition: { type: 'complete_module', moduleId: '02-food-ordering' },
    xpReward: 150,
  },
  {
    id: 'perfect-3',
    title: 'Bez chybičky',
    titleEn: 'Flawless',
    description: 'Score 100% on 3 fill-in-the-blank exercises',
    icon: '🎯',
    category: 'mastery',
    condition: { type: 'perfect_lesson', count: 3 },
    xpReward: 150,
  },
  {
    id: 'perfect-10',
    title: 'Perfekcionista',
    titleEn: 'Perfectionist',
    description: 'Score 100% on 10 fill-in-the-blank exercises',
    icon: '✨',
    category: 'mastery',
    condition: { type: 'perfect_lesson', count: 10 },
    xpReward: 300,
    hidden: true,
  },
  {
    id: 'practice-1h',
    title: 'Hodina tréninku',
    titleEn: 'Hour of Practice',
    description: 'Spend 1 hour practicing total',
    icon: '⏰',
    category: 'milestone',
    condition: { type: 'total_practice_time', minutes: 60 },
    xpReward: 200,
  },
];

export const MODULE_LIST: {
  id: string;
  title: string;
  titleEn: string;
  description: string;
  icon: string;
  estimatedMinutes: number;
  order: number;
  prerequisite?: string;
}[] = [
  {
    id: '01-greetings',
    title: 'Pozdravy',
    titleEn: 'Greetings & Survival',
    description: 'Greet people, introduce yourself, and use basic polite expressions',
    icon: '👋',
    estimatedMinutes: 20,
    order: 1,
  },
  {
    id: '02-food-ordering',
    title: 'Jídlo a pití',
    titleEn: 'Food & Drink Ordering',
    description: 'Order in restaurants, read menus, and handle payment',
    icon: '🍽️',
    estimatedMinutes: 25,
    order: 2,
    prerequisite: '01-greetings',
  },
  {
    id: '03-getting-around',
    title: 'Doprava',
    titleEn: 'Getting Around',
    description: 'Use public transport, buy tickets, and ask for directions',
    icon: '🚋',
    estimatedMinutes: 25,
    order: 3,
  },
  {
    id: '04-hotel-checkin',
    title: 'Ubytování',
    titleEn: 'Hotel Check-in',
    description: 'Check into hotels, handle reservations, and report issues',
    icon: '🏨',
    estimatedMinutes: 20,
    order: 4,
  },
  {
    id: '05-small-talk',
    title: 'Nezávazná konverzace',
    titleEn: 'Small Talk',
    description: 'Chat about family, work, weather, and hobbies',
    icon: '💬',
    estimatedMinutes: 25,
    order: 5,
  },
  {
    id: '06-emergencies',
    title: 'Nouzové situace',
    titleEn: 'Emergency Phrases',
    description: 'Handle medical issues, lost items, and urgent situations',
    icon: '🆘',
    estimatedMinutes: 20,
    order: 6,
  },
  {
    id: '07-shopping',
    title: 'Nakupování',
    titleEn: 'Shopping',
    description: 'Navigate stores, ask about prices, sizes, and make purchases',
    icon: '🛍️',
    estimatedMinutes: 20,
    order: 7,
  },
  {
    id: '08-directions',
    title: 'Orientace',
    titleEn: 'Directions & Landmarks',
    description: 'Give and follow detailed directions, understand landmarks',
    icon: '🗺️',
    estimatedMinutes: 25,
    order: 8,
  },
];
